### ISSUE TITLE
requirement file

### ISSUE THREAD

**Issue by chengzchengzhan** [Ugenteraan/Deep_Hierarchical_Classification#1]
Hi Ugenteraan Manogaran,

This is great, would you also provide a requirements.txt file?
Thanks!

best
Cheng

**Comment by Ugenteraan** [comment]
Hi Cheng,

I've added the Conda packages that I've used to run the code in the repo. There might be extra packages in requirements.txt that are not needed for this project. Please double-check before installing any packages. 

Thanks,
Ugenteraan
